version: "3.7"

services:
  psql_proxy:
    build:
      context: .
      dockerfile: ./docker/psql
    container_name: psql_proxy
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


  web:
    build:
      context: .
      dockerfile: ./docker/web
    container_name: web
    command: ["./docker/web.sh"]
    env_file:
      - .env_compose
    ports:
      - 8000:8000
    depends_on:
      psql_proxy:
        condition: service_healthy

